### ISSUE TITLE
SFTPClient.get() got an unexpected keyword argument 'prefetch'

### ISSUE THREAD

**Issue by hulleyrob** [byteskeptical/sftpretty#57]
Upgraded to Python 3.10 and reinstalled all the packages I use and now I get the above error.

Any ideas as this was working fine in 3.9 and ive just tried 3.12 and thats fine also.

I think for now I will just force my program to use 3.12.

Im trying to work out whether this was caused from moving an old Mac from Homebrew to Macports or there is some other issue.

**Comment by byteskeptical** [comment]
The first thing coming to mind is the underlying paramiko version being < 2.8.0 when the prefetch param was added, though I'm not sure why that would change with the python version itself.

**Comment by hulleyrob** [comment]
Thanks you have helped me solve it, due to the messing around moving between homebrew now it's no longer working/supported on Catalina and macports i somehow got version 2.7.2. Upgrading it fixed the problem.
