### PR TITLE
Sock Drawer

### LINKED ISSUE #67: Version 1.1.9 seems to keep open TCP connections after `connection.close()`
In version 1.1.9, the TCP connections stay open after calling `connection.close()`. We noticed this because we proxy the connection through nginx, which ended up keeping open hundreds of sockets, eventually hitting its open file limit.

The cause of this is _probably_ the new channel cache, although we haven't fully debugged the issue yet, but I already wanted to let you know (and potentially others using sftpretty). For now, we downgraded back to 1.1.8.

### LINKED ISSUE #70: _channel.close() AttributeError: 'NoneType' object has no attribute 'close'
I switched from pysftp to sftpretty to overcome [this recent issue][1] with paramiko v4.0.0,

sftpretty showed to be an easy replacement and works with paramiko v4.0.0,

nevertheless I'm facing repeated errors when an connection ends with an unexpected EOF

    paramiko/sftp.py", line 199, in _read_all
    raise EOFError()
    ...
    paramiko/sftp_client.py", line 132, in __init__
    raise SSHException("EOF during negotiation")
    ....
    sftpretty/__init__.py", line 322, in _sftp_channel
    _channel.close()
    AttributeError: 'NoneType' object has no attribute 'close'

Sorry, hard for me to reproduce a EOF, this is the 3rd that this happens today

[1]: https://github.com/paramiko/paramiko/issues/2537

### PR DESCRIPTION
**Pull request by byteskeptical**
Don't leave socks lying around.

### CODE REVIEW

**Comment by byteskeptical** [comment]
Need to follow-up on upstream changes in windows behavior for versions > 3.13
